apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    azure:
      secretStorage:
        keyVaultName: organic-spaniel
      storage:
        storageAccountName: jxorganicspaniel
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    environmentGitOwner: vnemane
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: aks
    registry: organicspaniel.azurecr.io
  environments:
  - key: dev
    owner: vnemane
    repository: jx3azurekey
  - key: staging
  - key: production
  ingress:
    domain: 20.40.125.83.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: virajnemane
  repository: nexus
  secretStorage: azurekeyvault
  storage:
  - name: logs
    url: azblob://logs
  vault: {}
  webhook: lighthouse
